### ISSUE TITLE
roslynanalyzers failing

### ISSUE THREAD

**Issue by jonteohr** [dotnet/code-analysis#21]
Hi, I'm trying to set this action up for a project I'm working on to analyze the code.
However every build fails with
```
Error:      Error running roslynanalyzers job: 1 of 1
Error:      GuardianErrorExitCodeException: roslynanalyzers completed with an Error exit code: 17. 
Error:      Error running tool 1 of 1: roslynanalyzers
Error:      Error running roslynanalyzers job: 1 of 1
Error:      GuardianErrorExitCodeException: roslynanalyzers completed with an Error exit code: 17. 
```

And I have no clue why. Below is my `.yml` file:
```yml
# sample-workflow-windows-latest
# docs are in the repo

# DISABLED for now - we do not support Ubuntu yet

name: .NET Code Analysis windows-latest
on:
  push:
    branches:
      - master

jobs:
  build:
    name: .NET Code Analysis runner

    # .NET Code Analysis runs on windows-latest.
    # ubuntu-latest and macos-latest supporting coming soon
    runs-on: windows-latest

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@v2

    # Ensure compatible versions of dotnet are installed.
    # The [Microsoft Code Analysis CLI](https://aka.ms/mscadocs) is built with dotnet v3.1.201.
    # A version greater than or equal to v3.1.201 of dotnet must be installed on the agent in order to run this action.
    # Remote agents already have a compatible version of dotnet installed and this step may be skipped.
    # For local agents, ensure dotnet version 3.1.201 or later is installed by including this action:
    # - uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: '3.1.x'

    # Run NuGet restore for the solution at repo root
    - name: Run NuGet restore
      run: dotnet restore .\C2TT.sln

    # Run code analysis for the solution at repo root
    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@main
      id: code-analysis
      with:
        project: .\C2TT.sln
        build-breaking: false
        all-categories: all

    # Upload the analysis results file
    - name: Upload analysis results
      uses: actions/upload-artifact@v2
      with:
        name: analysis_results.sarif
        path: ${{ steps.code-analysis.outputs.sarifFile }}
```
